# Generated by Django 4.0.4 on 2022-05-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_street_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='medicine_fk',
            field=models.ManyToManyField(to='index.medicines'),
        ),
    ]
