# Generated by Django 4.0.4 on 2022-05-19 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_address_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='medicine_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.medicines'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
