# Generated by Django 4.0.4 on 2022-05-25 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_remove_medicines_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='med_pac',
        ),
    ]
